# the header text
BLOG_NAME = "til"

# where the sqlite db is stored
SQLITE_PATH = "sqlite:///til.sqlite"

# username for authentication
USERNAME = None  # change to e.g. "username" to enable Basic Auth

# PBKDF2 salt
SALT = b"you should change this to something random!"

# PBKDF2 iteration count
ITERATIONS = 10000

# a password hash using the above SALT and ITERATIONS config.
# can be generated by `python til.py $YOUR_PASSWORD_HERE`
PASSWORD_HASH = b"b01bdaca4c9cf7cb056fbbf1f4763bf64c838ceda6c332f918ac6c481606fe78"
